version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: m.a.r.k.
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: m.a.r.k.
      POSTGRES_DB: java
    ports:
      - "5433:5432"
    networks:
      - my-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres-s-data: